version: '3'

vars:
  MODULE_NAME: api_server.main

tasks:
  setup:
    desc: Create a Python virtual environment
    cmds:
      - test -d .venv || uv venv

  install:
    desc: Install the package and development dependencies
    deps: [setup]
    cmds:
      - uv pip install --python .venv/bin/python -e '.[dev]'
      
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build/ dist/ *.egg-info .pytest_cache .ruff_cache __pycache__ .coverage
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - find . -type d -name "*.egg-info" -exec rm -rf {} +

  clean:all:
    desc: Clean all artifacts including virtual environment
    cmds:
      - task: clean
      - rm -rf .venv

  format:
    desc: Format code using ruff
    cmds:
      - .venv/bin/ruff format .

  lint:
    desc: Run ruff linter
    cmds:
      - .venv/bin/ruff check --fix .

  test:
    desc: Run tests with pytest
    cmds:
      - .venv/bin/python -m pytest {{.CLI_ARGS}}

  test:cov:
    desc: Run tests with coverage report
    cmds:
      - .venv/bin/python -m pytest --cov=src --cov-report=term-missing {{.CLI_ARGS}}

  check:
    desc: Run all code quality checks, excluding tests
    cmds:
      - task: format
      - task: lint

  build: 
    desc: Build the package
    cmds:
      - uv pip install --python .venv/bin/python build
      - .venv/bin/python -m build

  db:migrate:
    desc: Generate a new migration
    cmds:
      - .venv/bin/alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  db:upgrade:
    desc: Run all pending migrations
    cmds:
      - .venv/bin/alembic upgrade head

  db:downgrade:
    desc: Rollback the last migration
    cmds:
      - .venv/bin/alembic downgrade -1

  db:reset:
    desc: Reset the database (WARNING - This will delete all data)
    cmds:
      - task: db:upgrade

  run:
    desc: Run the application
    dotenv: ['.env']
    cmds:
      - .venv/bin/python -m {{.MODULE_NAME}} {{.CLI_ARGS}}

  run:cli:
    desc: Run the admin CLI (e.g. task run:cli -- db check)
    dotenv: ['.env']
    cmds:
      - .venv/bin/python -m api_server.cli {{.CLI_ARGS}}

  fct:
    desc: Format, check, test
    cmds:
      - task: format
      - task: check
      - task: test

  rebuild:all:
    desc: Clean, install, format/check/test, build, docker
    cmds:
      - task: clean:all
      - task: install
      - task: fct
      - task: build
      - task: docker:build

  pre-commit:install:
    desc: Install pre-commit hooks
    deps: [setup]
    cmds:
      - .venv/bin/pre-commit install --install-hooks

  pre-commit:update:
    desc: Update pre-commit hooks
    deps: [setup]
    cmds:
      - .venv/bin/pre-commit autoupdate

  pre-commit:run:
    desc: Run pre-commit hooks on all files
    deps: [setup]
    cmds:
      - .venv/bin/pre-commit run --all-files

  pre-commit:uninstall:
    desc: Uninstall pre-commit hooks
    deps: [setup]
    cmds:
      - .venv/bin/pre-commit uninstall

  docker:build:
    desc: Build Docker image for api-server
    cmd: docker build -t api-server .
